### ISSUE TITLE
refactor conf.py to include a nested version of cogent3 docs

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3.github.io#22]
We need to solve the following problem. Copy the `cogent3/doc` into `cogent3.github.io/doc/doc`. How do we then do the following

```
$ cd cogent3.github.io/doc
$ make html
```
and it correctly builds the documentation AND the sphinx gallery.

**Note:** you'll need to use the attached version of `cogent3.github.io/doc` [index.rst.zip](https://github.com/cogent3/cogent3.github.io/files/4590112/index.rst.zip)

Don't commit any code into repo, just post a tarball (`$ tar zcf dirname.tar.gz dirname`).

**Comment by u6052029** [comment]
Version of conf to build gallery under dev directory.
[conf.zip](https://github.com/cogent3/cogent3.github.io/files/4590787/conf.zip)

**Comment by GavinHuttley** [comment]
I've been looking at the [docs for seaborn](http://seaborn.pydata.org/), which use the same bootstrap theme. They have a really nice looking landing page, which is partly encoded using [explicit html in their index.rst file](https://raw.githubusercontent.com/mwaskom/seaborn/master/doc/index.rst).

It's not clear to me how they get their content to span the entire page width, i.e. width of their nav bar at the top and their body content below are the same

**Comment by GavinHuttley** [comment]
OK, we need to add our own css ([as seaborn has done](https://github.com/mwaskom/seaborn/blob/master/doc/_static/style.css#L63)), line reference is specific to [this github issue](https://github.com/twbs/bootstrap/issues/1768) which we have also noted

**Comment by GavinHuttley** [comment]
fixed in 8ee683d5089f8f899feaae2eb3adf60eb7c71bc4
